<a href="https://colab.research.google.com/github/asupraja3/py-ml-toolkit-collab/blob/main/numpy_collab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
lst = [1,2,3,4,5]
print(lst)

print('1D Array')
a = np.array([1,4,6,7,8])
print(a)

print('2D Array')
b = np.array([[1,4,6,7,8],[7,8,9,6,6]])
print(b)

[1, 2, 3, 4, 5]
1D Array
[1 4 6 7 8]
2D Array
[[1 4 6 7 8]
 [7 8 9 6 6]]


In [2]:
type(a) #n-dimensional array

numpy.ndarray

In [3]:
#number of elements in the array
print(a.size)
print(b.size)

5
10


In [4]:
#rows and columns
print(a.shape)
print(b.shape)

(5,)
(2, 5)


In [5]:
#type of data
print(a.dtype)

int64


In [7]:
#Transpose: row to columns, columns to rows
print(b.transpose())

[[1 7]
 [4 8]
 [6 9]
 [7 6]
 [8 6]]


In [10]:
#create an empty array
a = np.empty((4,4),dtype=int)
print(a) #Random 2-d array created

[[   449553625            0 489626271861 433791696995]
 [498216206368 468151435365 476741369968 416611827826]
 [450971566194 519691042924 502511173664 416611827822]
 [416611827830 463856468073 420906795105 433791697004]]


In [16]:
#np.ones
x = np.ones((3,5))
print(x)
x = np.ones((3,5),dtype = int)
print(x)
y= np.zeros(5)
print(y)
z = np.zeros((2,2), dtype=bool)
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[0. 0. 0. 0. 0.]
[[False False]
 [False False]]


In [17]:
#A-Range
a = np.arange(1,20,2)
print(a)


[ 1  3  5  7  9 11 13 15 17 19]
